//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2test4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class learnthinksavedbEntities1 : DbContext
    {
        public learnthinksavedbEntities1()
            : base("name=learnthinksavedbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudioURLTrascribedStringTAB> AudioURLTrascribedStringTAB { get; set; }
        public virtual DbSet<Table_Test> Table_Test { get; set; }
        public virtual DbSet<UserIdentityTAB> UserIdentityTAB { get; set; }
    }
}
