//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2test4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Test
    {
        public int test1 { get; set; }
        public string test4 { get; set; }
        public string test5 { get; set; }
    }
}
