//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2test4
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserIdentityTAB
    {
        public int userid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> school { get; set; }
        public Nullable<int> city { get; set; }
        public string langforcomm { get; set; }
    }
}
