//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplearnEF.ver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioURLTrascribedStringTAB
    {
        public int AudioId { get; set; }
        public string AudioURL { get; set; }
        public string TranscribedText { get; set; }
        public Nullable<byte> lang { get; set; }
    }
}
