//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplearnEF.ver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListofQuestionsWithDetailsofEachQuestionTAB
    {
        public long QuestionNo { get; set; }
        public string Lang { get; set; }
        public string QuestionType { get; set; }
        public Nullable<bool> E1QuestionUseText { get; set; }
        public string E1QuestionText { get; set; }
        public string E1QuestionAudio { get; set; }
        public Nullable<int> HowManyChoicesforAnswer { get; set; }
        public Nullable<bool> E2Option1UseText { get; set; }
        public string E2Option1Text { get; set; }
        public string E2Option1Audio { get; set; }
        public string E2Option1SpeechEngPhrasesXML { get; set; }
        public Nullable<bool> E3Option2UseText { get; set; }
        public string E3Option2Text { get; set; }
        public string E3Option2Audio { get; set; }
        public string E3Option2SpeechEngPhrasesXML { get; set; }
        public Nullable<bool> E4Option3UseText { get; set; }
        public string E4Option3Text { get; set; }
        public string E4Option3Audio { get; set; }
        public string E4Option3SpeechEngPhrasesXML { get; set; }
    }
}
