//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplearnEF.ver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTAB
    {
        public long StudentRollNo { get; set; }
        public Nullable<long> AssociatedPhoneNo { get; set; }
        public Nullable<bool> IsthePhoneNoShared { get; set; }
        public string StudentName { get; set; }
        public string StudentAddresableName { get; set; }
        public Nullable<int> ClassStd { get; set; }
        public string Lang { get; set; }
        public string Board { get; set; }
        public Nullable<System.DateTime> LastCall { get; set; }
        public string LastCallCompletionStatus { get; set; }
        public Nullable<int> LastCallPhCoachSessionNo { get; set; }
        public string LastCallSubject { get; set; }
        public string StudentAddresableNameAudioURL { get; set; }
        public Nullable<bool> IsAddressStudentByAudio { get; set; }
        public string AssociatedPhoneNoE164 { get; set; }
    }
}
