//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplearnEF.ver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubscriptionProgressionTAB
    {
        public Nullable<long> StudentRollNo { get; set; }
        public Nullable<int> ClassStd { get; set; }
        public string Lang { get; set; }
        public string Board { get; set; }
        public string Subject { get; set; }
        public Nullable<int> CurrentPhCoachSessionNo { get; set; }
        public long UniqueRowDummy { get; set; }
    }
}
